### PR TITLE
Cherry picking undo/redo fix

### PR DESCRIPTION
**Pull request by miketineo**
Cherrypicking changes from https://github.com/guardian/scribe/pull/480 to fix issues inserting polish character ż

@shajith @kencheeto @vcekov @roseleaf
### References

https://github.com/zendesk/zendesk_editor/pull/398

### CODE REVIEW

**Comment by pdeuter** [comment]
+1  yes, this cherry-pick looks like it's faithful to the original bug fix.

**Comment by kencheeto** [comment]
:+1:

**Comment by kencheeto** [comment]
Could you follow up with a pr to zendesk_editor so we don't miss this?

**Comment by miketineo** [comment]
Yes, I was planning to do that and the lotus PR as well

**Comment by kencheeto** [comment]
<3

**Pull request merged**
